# Set door position calibration

float32 cw      # Encoder duty cycle values for max CW
float32 zero    # Encoder duty cycle values for ZERO
float32 ccw     # Encoder duty cycle values for max CCW
---
bool success
string message
